-- Foydali ma'lumotlar: traffic sign reference (number, category, title, description, image).
-- Images live in the public 'foydali malumotlar' Supabase Storage bucket (created manually
-- by the site owner), image_path stores just the filename within that bucket.

CREATE TABLE public.traffic_signs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number text NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  image_path text,
  order_index integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.traffic_signs ENABLE ROW LEVEL SECURITY;
-- No policies: only edge functions (service-role key) touch this table.
CREATE INDEX idx_traffic_signs_category ON public.traffic_signs (category, order_index);

INSERT INTO public.traffic_signs (number, category, title, description, image_path, order_index) VALUES
('1.1', 'Ogohlantiruvchi belgilar', 'Shlagbaumli temir yo‘l kesishmasi', '', '1.1_resize-min.png.webp', 0),
('1.2', 'Ogohlantiruvchi belgilar', 'Shlagbaumsiz temir yo‘l kesishmasi', '', '1.2_resize-min.png.webp', 1),
('1.3.1', 'Ogohlantiruvchi belgilar', 'Bir izli temir yo‘l', 'Bir izli temir yo’l belgilari shlagbaum bilan jihozlanmagan temir yo’l kesishmasi oldida o’rnatiladi.', '1.3.1_resize-min.png', 2),
('1.3.2', 'Ogohlantiruvchi belgilar', 'Ko‘p izli temir yo‘l', 'Ikki va undan ortiq izli temir yo’l belgilari shlagbaum bilan jihozlanmagan temir yo’l kesishmasi oldida o’rnatiladi.', '1.3.2_resize-min.png.webp', 3),
('1.4.1 – 1.4.6', 'Ogohlantiruvchi belgilar', 'Temir yo‘l kesishmasiga yaqinlashuv', 'Aholi punktlaridan tashqarida temir yo‘l kesishmasiga yaqinlashayotganlik haqida qo‘shimcha ogohlantirish beradi.', '1.4_resize-230x300.png.webp', 4),
('1.5', 'Ogohlantiruvchi belgilar', 'Tramvay yo‘li bilan kesishuv', '', '1.5_resize-min.png.webp', 5),
('1.6', 'Ogohlantiruvchi belgilar', 'Teng ahamiyatli yo‘llar kesishuvi', '', '1.6_resize-min.png.webp', 6),
('1.7', 'Ogohlantiruvchi belgilar', 'Aylanma harakatlanish bilan kesishuv', '', '1.7_resize-min.png.webp', 7),
('1.8', 'Ogohlantiruvchi belgilar', 'Svetofor bilan tartibga solish', 'Harakatlanish svetofor bilan tartibga solinadigan chorraha, piyodalar o‘tish joyi yoki yo‘l qismini bildiradi.', '1.8_resize-min.png.webp', 8),
('1.9', 'Ogohlantiruvchi belgilar', 'Ko‘tarma ko‘prik', 'Ko‘tarma ko‘prik yoki solda kesib o‘tish.', '1.9_resize-min.png.webp', 9),
('1.10', 'Ogohlantiruvchi belgilar', 'Sohilga chiqish', 'Daryo yoki suv havzasi qirg‘og‘iga chiqishni bildiradi.', '1.10_resize-min.png.webp', 10),
('1.11.1', 'Ogohlantiruvchi belgilar', 'Xavfli burilish o‘ngga', 'O‘ngga yo‘l belgilari yo‘lning kichik radiusli yoki ko‘rinishi cheklangan burilish joyini bildiradi.', '1.11.1_resize-min.png.webp', 11),
('1.11.2', 'Ogohlantiruvchi belgilar', 'Xavfli burilish chapga', 'Chapga yo‘l belgilari yo‘lning kichik radiusli yoki ko‘rinishi cheklangan burilish joyini bildiradi.', '1.11.2_resize-min.png.webp', 12),
('1.12.1', 'Ogohlantiruvchi belgilar', 'Xavfli burilishlar', 'Birinchi burilish o‘ngga yo‘l belgilari yo‘lning xavfli burilishlari bo‘lgan qismini bildiradi.', '1.12.1_resize-min.png.webp', 13),
('1.12.2', 'Ogohlantiruvchi belgilar', 'Xavfli burilishlar', 'Birinchi burilish chapga yo‘l belgilari yo‘lning xavfli burilishlari bo‘lgan qismini bildiradi.', '1.12.2_resize-min.png.webp', 14),
('1.13', 'Ogohlantiruvchi belgilar', 'Tik nishablik', '', '1.13_resize-min.png.webp', 15),
('1.14', 'Ogohlantiruvchi belgilar', 'Tik balandlik', '', '1.14_resize-min.png.webp', 16),
('1.15', 'Ogohlantiruvchi belgilar', 'Sirpanchiq yo‘l', 'Qatnov qismi o‘ta sirpanchiq bo‘lgan yo‘l qismi.', '1.15_resize-min.png.webp', 17),
('1.16', 'Ogohlantiruvchi belgilar', 'Notekis yo‘l', 'Qatnov qismi notekis bo‘lgan yo‘l (o‘nqir-cho‘nqir, o‘ydim-chuqur joylar, ko‘prikning yo‘lga notekis tutashuvi va shu kabilar) qismini bildiradi.', '1.16_resize-min.png.webp', 18),
('1.17', 'Ogohlantiruvchi belgilar', 'Tosh otilishi xavfi', 'Transport vositasining g‘ildiragi ostidan shag‘al, tosh va shunga o‘xshashlarning otilib chiqish ehtimoli bo‘lgan yo‘l qismini bildiradi.', '1.17_resize-min.png.webp', 19),
('1.18.1', 'Ogohlantiruvchi belgilar', 'Yo‘lning torayishi', 'Ikki tomonlama torayish', '1.18.1_resize-min.png.webp', 20),
('1.18.2', 'Ogohlantiruvchi belgilar', 'Yo‘lning torayishi', 'O‘ngga torayish', '1.18.2_resize-min.png.webp', 21),
('1.18.3', 'Ogohlantiruvchi belgilar', 'Yo‘lning torayishi', 'Chapga torayish', '1.18.3_resize-min.png.webp', 22),
('1.19', 'Ogohlantiruvchi belgilar', 'Ikki tomonlama harakatlanish', 'Yo‘lning (qatnov qismining) qarama-qarshi harakatlanish qismi boshlanishini bildiradi.', '1.19_resize-min.png.webp', 23),
('1.20', 'Ogohlantiruvchi belgilar', 'Piyodalar o‘tish joyi', '5.16.1, 5.16.2, 5.48 belgilari va (yoki) 1.14.1 — 1.14.4, 1.29.1 — 1.29.3 yo‘l chiziqlari bilan belgilangan piyodalar o‘tish joyini bildiradi.', '1.20_resize-min.png.webp', 24),
('1.21', 'Ogohlantiruvchi belgilar', 'Bolalar', 'Bolalar muassasasi (maktablar, bolalarning dam olish maskanlari va shunga o‘xshashlar)ga yaqin yo‘lning qatnov qismidan bolalarning chiqib qolish ehtimolini bildiradi.', '1.21_resize-min.png.webp', 25),
('1.22', 'Ogohlantiruvchi belgilar', 'Velosiped yo‘lkasi bilan kesishuv', '', '1.22_resize-min.png.webp', 26),
('1.23', 'Ogohlantiruvchi belgilar', 'Ta’mirlash ishlari', '', '1.23_resize-min.png.webp', 27),
('1.24', 'Ogohlantiruvchi belgilar', 'Mol haydab o‘tish', '', '1.24_resize-min.png.webp', 28),
('1.25.1', 'Ogohlantiruvchi belgilar', 'Yovvoyi hayvonlar', '', '1.25.1_resize-min.png.webp', 29),
('1.25.2', 'Ogohlantiruvchi belgilar', 'Pastlab uchuvchi qushlar', '', '1.25.2_resize-min.png.webp', 30),
('1.25.3', 'Ogohlantiruvchi belgilar', 'Kemiruvchi va sudralib yuruvchi hayvonlar', '', '1.25.3_resize-min.png.webp', 31),
('1.26', 'Ogohlantiruvchi belgilar', 'Toshlar tushishi', 'Tosh ko‘chishi, surilishi va tushishi mumkin bo‘lgan yo‘l qismini bildiradi.', '1.26_resize-min.png.webp', 32),
('1.27', 'Ogohlantiruvchi belgilar', 'Yonlama shamol', '', '1.27_resize-min.png.webp', 33),
('1.28', 'Ogohlantiruvchi belgilar', 'Pastlab uchuvchi samolyotlar', '', '1.28_resize.png.webp', 34),
('1.29', 'Ogohlantiruvchi belgilar', 'Tunnel', 'Sun’iy ravishda yoritilmagan yoki kirish peshtog‘ining ko‘rinishi cheklangan tunnelni bildiradi.', '1.29_resize-min.png.webp', 35),
('1.30', 'Ogohlantiruvchi belgilar', 'Boshqa xavf-xatarlar', 'Ogohlantiruvchi belgilarda ko‘zda tutilmagan xavf-xatarlar bo‘lgan yo‘l qismini bildiradi.', '1.30_resize-min.png.webp', 36),
('1.31', 'Ogohlantiruvchi belgilar', 'Sun’iy yo‘l notekisligi', 'Yo‘lning sun’iy notekislik o‘rnatilgan qismiga yaqinlashayotganligi to‘g‘risida ogohlantiradi. Transport vositasining harakatlanish tezligini majburiy tarzda kamaytirish uchun qo‘llaniladi.', '1.31_resize-min.png.webp', 37),
('1.31.1 – 1.31.2', 'Ogohlantiruvchi belgilar', 'Burilishning yo‘nalishi', 'Kichik radiusli, ko‘rinishi cheklangan yo‘lda harakatlanish yo‘nalishini va yo‘lning ta’mirlanayotgan qismini aylanib o‘tish yo‘nalishini bildiradi.', '1.31.1_resize-min.png.webp', 38),
('1.31.3', 'Ogohlantiruvchi belgilar', 'Burilishning yo‘nalishi', 'T-simon chorrahada yoki yo‘l ayrilishlarida harakatlanish yo‘nalishini, ta’mirlanayotgan yo‘l qismini aylanib o‘tish yo‘nalishini bildiradi.', '1.31.3_resize-min.png', 39),
('1.32', 'Ogohlantiruvchi belgilar', 'Tirbandlik', 'Ushbu yo‘l belgisi vaqtinchalik yoki tasviri o‘zgaradigan holatda tirbandlik hosil bo‘lgan yo‘l yoki chorrahaga kirish oldidan yo‘lni yoki chorrahani aylanib o‘tish imkoniyati bo‘lgan joyga o‘rnatiladi.', '1.32_resize-min.png.webp', 40),
('1.33', 'Ogohlantiruvchi belgilar', 'Qatnov qismi kesishmasi hududi', '1. 30 yotiq chizig‘i bilan belgilangan chorrahaga yaqinlashayotganligini anglatib, oldinda tirbandlik yuzaga kelganligi tufayli majburiy to‘xtab, ko‘ndalang yo‘nalishdagi transport vositalarining harakatlanishiga to‘sqinlik tug‘diradigan bo‘lsa, chorrahaga kirish, agar to‘xtash chizig‘i yoki 5.33 yo‘l belgisidan o‘tib bo‘lgan haydovchiga esa qatnov qismlari kesishmasiga kirishni taqiqlanishini bildiradi.', '1.33_resize-min.png.webp', 41),
('1.34', 'Ogohlantiruvchi belgilar', 'Diqqat, boshqariladigan to‘siq', 'Ushbu yo‘l belgisi boshqariladigan to‘suvchi qurilmasiga yetmasdan o‘rnatiladi va transport vositalari haydovchilarini oldinda to‘suvchi qurilma borligi haqida ogohlantiradi.', '1.34_resize-min.png.webp', 42),
('1.35', 'Ogohlantiruvchi belgilar', 'Piyodalarning yo‘l yoqasidan yurishi mumkin bo‘lgan hudud', '', '1.35_resize-min.png.webp', 43),
('2.1', 'Imtiyoz belgilari', 'Asosiy yo‘l', 'Harakat tartibga solinmagan chorrahalarda oldin o‘tish huquqini beradi. Belgi asosiy yo‘l boshiga va chorrahalarning bevosita oldiga o‘rnatiladi.', '2.1_resize-min.png', 44),
('2.2', 'Imtiyoz belgilari', 'Asosiy yo‘lning oxiri', '', '2.2_resize-min.png', 45),
('2.3.1', 'Imtiyoz belgilari', 'Ikkinchi darajali yo‘l bilan kesishuv', 'Yo‘l belgilari aholi punktlarida kesishmagacha 50 — 100 metr masofada, aholi punktlaridan tashqarida esa 150 — 300 metr masofada o‘rnatiladi.', '2.3.1.1_resize-min.png.webp', 46),
('2.3.2', 'Imtiyoz belgilari', 'Ikkinchi darajali yo‘l bilan tutashuv o‘ngdan', 'Yo‘l belgilari aholi punktlarida kesishmagacha 50 — 100 metr masofada, aholi punktlaridan tashqarida esa 150 — 300 metr masofada o‘rnatiladi.', '2.3.2.1_resize-min.png.webp', 47),
('2.3.3', 'Imtiyoz belgilari', 'Ikkinchi darajali yo‘l bilan tutashuv chapdan', 'Yo‘l belgilari aholi punktlarida kesishmagacha 50 — 100 metr masofada, aholi punktlaridan tashqarida esa 150 — 300 metr masofada o‘rnatiladi.', '2.3.3.1_resize-min.png.webp', 48),
('2.4', 'Imtiyoz belgilari', 'Yo‘l bering', 'Haydovchi kesib o‘tilayotgan yo‘ldan, 7.13 qo‘shimcha-axborot belgisi bo‘lganda esa asosiy yo‘ldan harakatlanayotgan transport vositasiga yo‘l berishi kerak.', '2.4_resize-min.png.webp', 49),
('2.5', 'Imtiyoz belgilari', 'To‘xtamasdan harakatlanish taqiqlangan', 'To‘xtash chizig‘i oldida, agar u bo‘lmasa, kesib o‘tiladigan qatnov qismining chetida to‘xtamasdan harakatlanish taqiqlanadi. Haydovchi kesib o‘tilayotgan yo‘ldan, 7.13 qo‘shimcha-axborot belgisi bo‘lganda esa asosiy yo‘ldan harakatlanayotgan transport vositalariga yo‘l berishi kerak. Bu belgi temir yo‘l kesishmasi yoki karantin maskanidan oldin o‘rnatilishi mumkin. Bunday hollarda haydovchi to‘xtash chizig‘i oldida, u bo‘lmasa, belgi oldida to‘xtashi kerak.', '2.5_resize-min.png.webp', 50),
('2.6', 'Imtiyoz belgilari', 'Ro‘para harakatlanishning ustunligi', 'Qarama-qarshi harakatlanishni qiyinlashtiradigan hollarda yo‘lning tor qismiga kirish taqiqlanadi. Haydovchi yo‘lning tor qismida bo‘lgan yoki ro‘paradan unga yaqin bo‘lgan transport vositasiga yo‘l berishi kerak.', '2.6_resize-min.png.webp', 51),
('2.7', 'Imtiyoz belgilari', 'Ro‘paradagi harakatlanishga nisbatan imtiyoz', 'Yo‘lning tor qismida harakatlanishda haydovchi ro‘paradan kelayotgan transport vositasiga nisbatan imtiyozga egaligini bildiradi.', '2.7_resize-min.png.webp', 52),
('3.1', 'Taqiqlovchi belgilar', 'Kirish taqiqlangan', 'Barcha transport vositalarining kirishi taqiqlanishini bildiradi.', '3.1_resize-min.png.webp', 53),
('3.2', 'Taqiqlovchi belgilar', 'Harakatlanish taqiqlangan', 'Barcha transport vositalarining harakatlanishi taqiqlanishini bildiradi.', '3.2_resize-min.png.webp', 54),
('3.3', 'Taqiqlovchi belgilar', 'Mexanik transport vositalarining harakatlanishi taqiqlangan', '', '3.3_resize-min.png.webp', 55),
('3.4', 'Taqiqlovchi belgilar', 'Yuk avtomobillarining harakatlanishi taqiqlangan', 'Ruxsat etilgan to‘liq vazni 3,5 tonnadan (agar vazni belgida ko‘rsatilmagan bo‘lsa) yoki ruxsat etilgan to‘liq vazni belgida ko‘rsatilgandan ortiq bo‘lgan yuk avtomobillari va transport vositalari tarkiblarining, shuningdek traktorlar, o‘ziyurar uskunalarning harakatlanishi taqiqlanadi. 3.4. yo‘l belgisi bortlariga qiya oq chiziq tortilgan yoki odamlarni tashish uchun mo‘ljallangan yuk avtomobillarining harakatlanishini taqiqlamaydi.', '3.4_resize-min.png.webp', 56),
('3.5', 'Taqiqlovchi belgilar', 'Mototsikllar harakatlanishi taqiqlangan', '', '3.5_resize-min.png.webp', 57),
('3.6', 'Taqiqlovchi belgilar', 'Traktorlar harakatlanishi taqiqlangan', 'Traktorlar va o‘ziyurar uskunalarning harakatlanishi taqiqlanadi.', '3.6_resize-min.png.webp', 58),
('3.7', 'Taqiqlovchi belgilar', 'Tirkama bilan harakatlanish taqiqlangan', 'Yuk avtomobillari va traktorlarning barcha turdagi tirkamalar bilan harakatlanishi, shuningdek, mexanik transport vositalarini shatakka olish taqiqlanadi.', '3.7_resize-min.png.webp', 59),
('3.8', 'Taqiqlovchi belgilar', 'Ot-arava harakatlanishi taqiqlangan', 'Ot-arava (chana), otliqlar, yuk ortilgan hayvonlarning harakatlanishi, shuningdek, chorva (poda) haydab o‘tish taqiqlanadi.', '3.8_resize-min.png.webp', 60),
('3.9', 'Taqiqlovchi belgilar', 'Velosipedda harakatlanish taqiqlangan', 'Velosipedda va mopedda harakatlanish taqiqlanadi.', '3.9_resize-min.png.webp', 61),
('3.10', 'Taqiqlovchi belgilar', 'Piyodaning harakatlanishi taqiqlangan', '', '3.10_resize-min.png.webp', 62),
('3.11', 'Taqiqlovchi belgilar', 'Vazn cheklangan', 'Haqiqiy umumiy vazni belgida ko‘rsatilganidan ortiq bo‘lgan transport vositalarining, shuningdek, transport vositalari tarkiblarining harakatlanishi taqiqlanadi.', '3.11_resize.png.webp', 63),
('3.12', 'Taqiqlovchi belgilar', 'O‘qqa tushadigan og‘irlik cheklangan', 'Har qanday o‘qiga tushadigan haqiqiy og‘irlik belgida ko‘rsatilganidan ortiq bo‘lgan transport vositalarining harakatlanishi taqiqlanadi.', '3.12_resize-min.png.webp', 64),
('3.13', 'Taqiqlovchi belgilar', 'Cheklangan balandlik', 'Gabarit balandligi (yuk bilan yoki yuksiz) belgida ko‘rsatilgandan ortiq bo‘lgan transport vositalarining harakatlanishi taqiqlanadi.', '3.13_resize.png.webp', 65),
('3.14', 'Taqiqlovchi belgilar', 'Cheklangan kenglik', 'Gabarit kengligi (yuk bilan yoki yuksiz) belgida ko‘rsatilganidan ortiq bo‘lgan transport vositalarining harakatlanishi taqiqlanadi.', '3.14_resize.png.webp', 66),
('3.15', 'Taqiqlovchi belgilar', 'Cheklangan uzunlik', 'Gabarit uzunligi (yuk bilan yoki yuksiz) belgida ko‘rsatilganidan ortiq bo‘lgan transport vositalari (transport vositalari tarkiblari)ning harakatlanishi taqiqlanadi.', '3.15_resize-min.png.webp', 67),
('3.16', 'Taqiqlovchi belgilar', 'Eng kam oraliq', 'Belgida ko‘rsatilganidan kam bo‘ylama oraliq masofada harakatlanish taqiqlanadi.', '3.16_resize-min.png.webp', 68),
('3.17.1', 'Taqiqlovchi belgilar', 'Bojxona', 'Bojxona (nazorat punkti) oldida to‘xtamasdan o‘tib ketish taqiqlanadi.', '3.17.1_resize-min.png.webp', 69),
('3.17.2', 'Taqiqlovchi belgilar', 'Xavf-xatar', 'Yo‘l-transport hodisasi, avariya, yong‘in yoki boshqa xavf-xatar vaziyatlar tufayli, istisnosiz, barcha transport vositalarining bundan keyin harakatlanishi taqiqlanadi.', '3.17.2_resize-min.png.webp', 70),
('3.17.3', 'Taqiqlovchi belgilar', 'Nazorat joyi', 'Transport vositalarining tekshirib o‘tkazilishi majburiy bo‘lgan vaqtincha yoki doimiy nazorat punktlarida o‘rnatiladi. Ushbu yo‘l belgisi 2.5 yo‘l belgisi bilan birga o‘rnatilishi mumkin.', '3.17.3_resize-min.png.webp', 71),
('3.18.1', 'Taqiqlovchi belgilar', 'O‘ngga burilish taqiqlangan', '', '3.18.1_resize-min.png.webp', 72),
('3.18.2', 'Taqiqlovchi belgilar', 'Chapga burilish taqiqlanadi', '', '3.18.2_resize-min.png.webp', 73),
('3.19', 'Taqiqlovchi belgilar', 'Qayrilish taqiqlangan', '', '3.19_resize-min.png.webp', 74),
('3.20', 'Taqiqlovchi belgilar', 'Quvib o‘tish taqiqlangan', 'Soatiga 40 km dan kam tezlikda harakatlanayotgan yakka transport vositasidan boshqa transport vositalarini quvib o‘tish taqiqlanishini bildiradi.', '3.20_resize-min.png.webp', 75),
('3.21', 'Taqiqlovchi belgilar', 'Quvib o‘tish taqiqlangan hududning oxiri', '', '3.21_resize-min.png.webp', 76),
('3.22', 'Taqiqlovchi belgilar', 'Yuk avtomobillarida quvib o‘tish taqiqlangan', 'To‘liq vazni 3,5 tonnadan ortiq bo‘lgan yuk avtomobillarida barcha transport vositalarini quvib o‘tish taqiqlanishini bildiradi (soatiga 40 km dan kam tezlikda harakatlanayotgan transport vositasi, traktor, ot-arava, velosiped bundan mustasno).', '3.22_resize-min.png.webp', 77),
('3.23', 'Taqiqlovchi belgilar', 'Yuk avtomobillarida quvib o‘tish taqiqlangan hududning oxiri', '', '3.23.1_resize-min.png.webp', 78),
('3.24', 'Taqiqlovchi belgilar', 'Yuqori tezlik cheklangan', 'Belgida ko‘rsatilganidan ortiq tezlikda (km/s) harakatlanish taqiqlanishini bildiradi.', '3.24_resize-min.png.webp', 79),
('3.25', 'Taqiqlovchi belgilar', 'Yuqori tezlik cheklangan hududning oxiri', '', '3.25_resize-min.png.webp', 80),
('3.26', 'Taqiqlovchi belgilar', 'Tovush moslamalaridan foydalanish taqiqlangan', 'Yo‘l transport hodisasining oldini olish hollaridan boshqa vaziyatlarda tovush moslamasidan foydalanish taqiqlanadi.', '3.26_resize-min.png.webp', 81),
('3.27', 'Taqiqlovchi belgilar', 'To‘xtash taqiqlangan', 'Transport vositalarining to‘xtashi va to‘xtab turishi taqiqlanadi (xizmat vazifasini bajarayotgan xodimga biriktirilgan ko‘k yoki qizil yoxud ko‘k va qizil rangli yaltiroq mayoqchasi bilan jihozlangan hamda maxsus rangli bo‘yoq sxemalar va yozuvlar bilan belgilangan transport vositalari bundan mustasno).', '3.27_resize-min.png.webp', 82),
('3.28', 'Taqiqlovchi belgilar', 'To‘xtab turish taqiqlangan', 'Transport vositalarining to‘xtab turishi taqiqlanadi (xizmat vazifasini bajarayotgan xodimga biriktirilgan ko‘k yoki qizil yoxud ko‘k va qizil rangli yaltiroq mayoqchasi bilan jihozlangan hamda maxsus rangli bo‘yoq sxemalar va yozuvlar bilan belgilangan transport vositalari bundan mustasno).', '3.28_resize-min.png.webp', 83),
('3.29', 'Taqiqlovchi belgilar', 'Oyning toq kunlarida to‘xtab turish taqiqlangan', '(xizmat vazifasini bajarayotgan xodimga biriktirilgan ko‘k yoki qizil yoxud ko‘k va qizil rangli yaltiroq mayoqchasi bilan jihozlangan hamda maxsus rangli bo‘yoq sxemalar va yozuvlar bilan belgilangan transport vositalari bundan mustasno).', '3.29_resize-min.png.webp', 84),
('3.30', 'Taqiqlovchi belgilar', 'Oyning juft kunlarida to‘xtab turish taqiqlangan', '(xizmat vazifasini bajarayotgan xodimga biriktirilgan ko‘k yoki qizil yoxud ko‘k va qizil rangli yaltiroq mayoqchasi bilan jihozlangan hamda maxsus rangli bo‘yoq sxemalar va yozuvlar bilan belgilangan transport vositalari bundan mustasno).3.29 va 3.30 belgilari qatnov qismining qarama-qarshi tomonlarida bir vaqtda o‘rnatilganda, qatnov qismining har ikkala tomonida soat 19:00 dan 21:00 gacha to‘xtab turishga ruxsat etiladi (joyini o‘zgartirish vaqti).', '3.30_resize-min.png.webp', 85),
('3.31', 'Taqiqlovchi belgilar', 'Barcha cheklovlarning oxiri', '3.16, 3.20, 3.22, 3.24, 3.26 — 3.30 belgilaridan bir nechtasiga bir vaqtda amal qiladigan hududlarning oxiri.', '3.31_resize-min.png.webp', 86),
('3.32', 'Taqiqlovchi belgilar', 'Xavfli yuk tashiyotgan transport vositasining harakati taqiqlangan', '', '3.32_resize-min.png.webp', 87),
('3.33', 'Taqiqlovchi belgilar', 'Portlovchi va tez alangalanuvchi yukni tashiyotgan transport vositasining harakati taqiqlangan', '', '3.33_resize-min.png.webp', 88),
('4.1.1', 'Buyuruvchi belgilar', 'Harakatlanish to‘g‘riga', '', '4.1.1_resize-min.png.webp', 89),
('4.1.2', 'Buyuruvchi belgilar', 'Harakatlanish o‘ngga', '', '4.1.2_resize-min.png.webp', 90),
('4.1.3', 'Buyuruvchi belgilar', 'Harakatlanish chapga', '', '4.1.3_resize-min.png.webp', 91),
('4.1.4', 'Buyuruvchi belgilar', 'Harakatlanish to‘g‘riga yoki o‘ngga', '', '4.1.4_resize-min.png.webp', 92),
('4.1.5', 'Buyuruvchi belgilar', 'Harakatlanish to‘g‘riga yoki chapga', '', '4.1.5_resize-min.png.webp', 93),
('4.1.6', 'Buyuruvchi belgilar', 'Harakatlanish o‘ngga yoki chapga', '', '4.1.6_resize-min.png.webp', 94),
('4.2.1', 'Buyuruvchi belgilar', 'To‘siqni o‘ngdan aylanib o‘tish', 'Faqat ko‘rsatkich ko‘rsatgan tomondan aylanib o‘tish ruxsat etiladi.', '4.2.1_resize-min.png.webp', 95),
('4.2.2', 'Buyuruvchi belgilar', 'To‘siqni chapdan aylanib o‘tish', 'Faqat ko‘rsatkich ko‘rsatgan tomondan aylanib o‘tish ruxsat etiladi.', '4.2.2_resize-min.png.webp', 96),
('4.2.3', 'Buyuruvchi belgilar', 'To‘siqni o‘ngdan yoki chapdan aylanib o‘tish', 'Har tomonidan aylanib o‘tish ruxsat etiladi.', '4.2.3_resize-min.png.webp', 97),
('4.3', 'Buyuruvchi belgilar', 'Aylanma harakatlanish', 'Ko‘rsatkichlar yo‘nalishlarida harakatlanish ruxsat etiladi.', '4.3_resize-min.png.webp', 98),
('4.4', 'Buyuruvchi belgilar', 'Yengil avtomobillar harakati', 'Yengil avtomobillar, avtobus, mototsikllar, belgilangan yo‘nalishli transport vositalari va ruxsat etilgan to‘liq vazni 3,5 tonnadan oshmaydigan yuk avtomobillari harakatlanishiga ruxsat etilishini bildiradi. Belgining ta’sir oralig‘ida yashovchi va ishlovchi fuqarolarga tegishli, ularga va korxonalarga xizmat ko‘rsatuvchi transport vositalariga bu belgi tatbiq etilmaydi. Bunday hollarda transport vositalari belgilangan joyga eng yaqin chorrahadan kirib yoki chiqib ketishlari kerak.', '4.4_resize-min.png.webp', 99),
('4.5', 'Buyuruvchi belgilar', 'Velosiped yo‘lkasi', 'Faqat velosiped va mopedlarda harakatlanishga ruxsat etilishini bildiradi. Trotuar yoki piyodalar yo‘lkasi bo‘lmasa, velosiped yo‘lkasidan piyodalar ham yurishlari mumkin.', '4.5_resize-min.png.webp', 100),
('4.6', 'Buyuruvchi belgilar', 'Piyodalar yo‘lkasi', 'Faqat piyodalar yurishiga ruxsat etiladi.', '4.6.0_resize-min.png.webp', 101),
('4.6.1', 'Buyuruvchi belgilar', 'Piyodalar va velosipedchilarning birgalikdagi harakati tashkil etilgan yo‘lak', '', '4.6.1_resize-min.png.webp', 102),
('4.6.2', 'Buyuruvchi belgilar', 'Piyodalar va velosipedchilarning birgalikdagi harakati tashkil etilgan yo‘lakning oxiri', '', '4.6.2_resize-min.png.webp', 103),
('4.6.3', 'Buyuruvchi belgilar', 'Piyodalar va velosipedchilarning harakati alohida tashkil etilgan yo‘lak', '1.1, 1.25 va 1.26 yotiq yo‘l chizig‘i yordamida, konstruktiv tarzda yoxud boshqa usulda piyodalar va velosipedchilarning harakati ajratilgan piyodalar va velosipedchilar yo‘lagi.', '4.6.3_resize-min.png.webp', 104),
('4.6.4', 'Buyuruvchi belgilar', 'Piyodalar va velosipedchilarning harakati alohida tashkil etilgan yo‘lakning oxiri', '', '4.6.4_resize-min.png.webp', 105),
('4.6.5', 'Buyuruvchi belgilar', 'Piyodalar va velosipedchilarning harakati alohida tashkil etilgan yo‘lak', '1.1, 1.25 va 1.26 yotiq yo‘l chizig‘i yordamida, konstruktiv tarzda yoxud boshqa usulda piyodalar va velosipedchilarning harakati ajratilgan piyodalar va velosipedchilar yo‘lagi.', '4.6.5_resize-min.png.webp', 106),
('4.6.6', 'Buyuruvchi belgilar', 'Piyodalar va velosipedchilarning harakati alohida tashkil etilgan yo‘lakning oxiri', '', '4.6.6_resize-min.png.webp', 107),
('4.7', 'Buyuruvchi belgilar', 'Eng kam tezlik', 'Faqat belgida ko‘rsatilgan yoki undan yuqori tezlikda (km/soat) harakatlanishga ruxsat etilishini bildiradi.', '4.7_resize-min.png.webp', 108),
('4.8', 'Buyuruvchi belgilar', 'Eng kam tezlik belgilangan yo‘lning oxiri', '', '4.8_resize-min.png.webp', 109),
('4.9.1', 'Buyuruvchi belgilar', 'Xavfli yuk tashiyotgan transport vositalarining harakat yo‘nalishi', '«Xavfli yuk» tanish belgisi bilan jihozlangan transport vositalarining harakatiga yo‘l belgisida ko‘rsatilgan yo‘nalishlarda ruxsat beriladi: to‘g‘riga.', '4.9.1_resize-min.png.webp', 110),
('4.9.2', 'Buyuruvchi belgilar', 'Xavfli yuk tashiyotgan transport vositalarining harakat yo‘nalishi', '«Xavfli yuk» tanish belgisi bilan jihozlangan transport vositalarining harakatiga yo‘l belgisida ko‘rsatilgan yo‘nalishlarda ruxsat beriladi: chapga.', '4.9.2_resize-min.png.webp', 111),
('4.9.3', 'Buyuruvchi belgilar', 'Xavfli yuk tashiyotgan transport vositalarining harakat yo‘nalishi', '«Xavfli yuk» tanish belgisi bilan jihozlangan transport vositalarining harakatiga yo‘l belgisida ko‘rsatilgan yo‘nalishlarda ruxsat beriladi: o‘ngga.', '4.9.3_resize-min.png.webp', 112),
('5.1', 'Axborot belgilari', 'Avtomagistral', 'Yo‘l harakati qoidalarining avtomagistrallarda harakatlanish tartibi o‘rnatilgan yo‘lni bildiradi.', '5.1_resize-min.png.webp', 113),
('5.2', 'Axborot belgilari', 'Avtomagistralning oxiri', '', '5.2_resize-min.png.webp', 114),
('5.3', 'Axborot belgilari', 'Avtomobillar uchun mo‘ljallangan yo‘l', 'Faqat avtomobillar, avtobus va mototsikllarning harakatlanishi uchun mo‘ljallangan yo‘lni bildiradi.', '5.3_resize-min.png.webp', 115),
('5.4', 'Axborot belgilari', 'Avtomobillar uchun mo‘ljallangan yo‘lning oxiri', '', '5.4_resize-min.png.webp', 116),
('5.5', 'Axborot belgilari', 'Bir tomonlama harakatli yo‘l', 'Transport vositalari butun kenglik bo‘yicha bir yo‘nalishda harakatlanadigan yo‘l yoki qatnov qismi.', '5.5_resize-min.png.webp', 117),
('5.6', 'Axborot belgilari', 'Bir tomonlama harakatli yo‘lning oxiri', '', '5.6_resize-min.png.webp', 118),
('5.7.1 – 5.7.2', 'Axborot belgilari', 'Bir tomonlama harakatli yo‘lga chiqish', 'Harakatlanish bir tomonlama bo‘lgan yo‘lga yoki qatnov qismiga chiqish.', '5.7.1_resize-min.png.webp', 119),
('5.8.1', 'Axborot belgilari', 'Tasmalar bo‘yicha harakat yo‘nalishi', 'Tasmalar soni va har biri bo‘yicha ruxsat etilgan harakatlanish yo‘nalishlari. Boshqa yo‘nalishlar bo‘yicha harakatlanish taqiqlanadi.', '5.8.1_resize-min.png.webp', 120),
('5.8.2', 'Axborot belgilari', 'Tasma bo‘yicha harakatlanish yo‘nalishi', 'Tasma bo‘yicha ruxsat etilgan harakatlanish yo‘nalishi. Boshqa yo‘nalishlar bo‘yicha harakatlanish taqiqlanadi.', '5.8_resize-min-300x300.png.webp', 121),
('5.8.3', 'Axborot belgilari', 'Tasmaning boshlanishi', 'Yo‘lning sekinlashish bo‘lagi yoki balandlikka ko‘tarilishdagi qo‘shimcha tasmaning boshlanish qismi. Agar belgiga 4.7 “Eng kam tezlik” belgisining tasviri tushgan bo‘lsa, ko‘rsatilgan yoki undan kattaroq tezlikda harakatlana olmaydigan transport vositasining haydovchisi asosiy tasmadan qo‘shimcha tasmaga qayta tizilishi kerak.', '5.8.3_resize-min-149x300.png.webp', 122),
('5.8.4', 'Axborot belgilari', 'Tasmaning boshlanishi', 'Uch tasmali yo‘llarda shu yo‘nalishda harakatlanish uchun mo‘ljallangan o‘rta tasma qismining boshlanishi.', '5.8.4_resize-min.png.webp', 123),
('5.8.5', 'Axborot belgilari', 'Tasma oxiri', 'Balandlikka ko‘tarilishdagi qo‘shimcha tasmaning yoki tezlanish tasmaning oxirini bildiradi.', '5.8.5_resize-min.png.webp', 124),
('5.8.6', 'Axborot belgilari', 'Tasma oxiri', 'Uch tasmali yo‘llarda shu yo‘nalishda harakatlanish uchun mo‘ljallangan o‘rta tasma qismining oxirini bildiradi.', '5.8.6_resize-min.png.webp', 125),
('5.8.7 5.8.8', 'Axborot belgilari', 'Tasmalar bo‘yicha harakatlanish yo‘nalishi', 'Agar 5.8.7 belgisida biror transport vositasining harakatlanishini taqiqlovchi belgi tasvirlangan bo‘lsa, unda bu tur transport vositasining tegishli tasmada harakatlanishi taqiqlanishini bildiradi. 5.8.7 va 5.8.8 belgilari yo‘nalishlar soniga ko‘ra to‘rt va undan ortiq tasmali yo‘llarga ham tatbiq etilishi mumkin. Tasviri almashadigan 5.8.7, 5.8.8 belgilari yordamida reversiv harakat tashkil etilishi mumkin.', '5.8_resize-min-300x300.png.webp', 126),
('5.9', 'Axborot belgilari', 'Yo‘nalishli transport vositalari uchun mo‘ljallangan tasma', 'Transport vositalari yo‘nalishida harakatlanadigan yo‘nalishli transport vositalari uchun mo‘ljallangan tasmani bildiradi. Belgi qaysi tasma ustida joylashgan bo‘lsa, shu tasmaga tatbiq etiladi. Yo‘lning o‘ng tomoniga o‘rnatilgan belgining ta’siri o‘ng tasmaga tatbiq etiladi.', '5.9_resize-min.png.webp', 127),
('5.10.1', 'Axborot belgilari', 'Yo‘nalishli transport vositalari uchun alohida ajratilgan tasmasi bor yo‘l', 'Yo‘nalishli transport vositalarining umumiy oqimga qarshi harakatlanishi uchun ajratilgan tasmani bildiradi.', '5.10.1_resize-min.png.webp', 128),
('5.10.2 – 5.10.3', 'Axborot belgilari', 'Yo‘nalishli transport vositalari uchun alohida ajratilgan tasmasi bor yo‘lga chiqish', '', '5.10.2_resize-min.png.webp', 129),
('5.10.4', 'Axborot belgilari', 'Yo‘nalishli transport vositalari uchun alohida ajratilgan tasmasi bor yo‘lning oxiri', '', '5.10.4_resize-min.png.webp', 130),
('5.11.1', 'Axborot belgilari', 'Qayrilib olish joyi', 'Chapga burilish taqiqlanadi.', '5.11.1_resize-min.png.webp', 131),
('5.11.2', 'Axborot belgilari', 'Qayrilib olish oralig‘i', 'Qayrilib olish oralig‘ining uzunligini bildiradi. Chapga burilish taqiqlanadi.', '5.11.2_resize-min.png.webp', 132),
('5.12', 'Axborot belgilari', 'Avtobus va (yoki) trolleybus to‘xtash joyi', '', '5.12_resize-min.png.webp', 133),
('5.13', 'Axborot belgilari', 'Tramvay to‘xtash joyi', '', '5.13_resize-min.png.webp', 134),
('5.14', 'Axborot belgilari', 'Yo‘nalishsiz taksilar to‘xtab turish joyi', '', '5.14_resize-min.png.webp', 135),
('5.15', 'Axborot belgilari', 'To‘xtab turish joyi', '', '5.15_resize-min.png.webp', 136),
('5.15.1', 'Axborot belgilari', 'Pullik to‘xtab turish joyi', '', '5.15.1_resize-min.png.webp', 137),
('5.15.2', 'Axborot belgilari', 'Yer usti avtomobil qo‘yish joyi', '', '5.15.2_resize-min.png.webp', 138),
('5.15.3', 'Axborot belgilari', 'Yer osti avtomobil qo‘yish joyi', '', '5.15.3_resize-min.png.webp', 139),
('5.15.4', 'Axborot belgilari', 'Elektr quvvatlashli avtomobil qo‘yish joyi', '', '5.15.4_resize-min.png.webp', 140),
('5.16.1 – 5.16.2', 'Axborot belgilari', 'Piyodalar o‘tish joyi', 'O‘tish joyi oldida 1.14.1-1.14.2 yotiq chizig‘i bo‘lmaganda 5.16.2 belgisi yo‘ldan o‘ng tomonga o‘tish joyining old chegarasiga, 5.16.1 belgisi esa chap tomonga o‘tish joyining orqa chegarasiga o‘rnatiladi.', '5.16.1_resize-min.png.webp', 141),
('5.17.1 – 5.17.2', 'Axborot belgilari', 'Piyodalarning yer ostidan o‘tish joyi', '', '5.17.1_resize-min.png.webp', 142),
('5.17.3 – 5.17.4', 'Axborot belgilari', 'Piyodalarning yer ustidan o‘tish joyi', '', '5.17.3_resize-min.png.webp', 143),
('5.18', 'Axborot belgilari', 'Tavsiya etilgan tezlik', 'Yo‘lning shu qismida tavsiya etilgan harakatlanish tezligini bildiradi. Belgiga eng yaqin chorrahagacha amal qilinadi. 5.18 belgisi ogohlantiruvchi belgi bilan birga qo‘llansa, uning ta’sir oralig‘i xavfli qismning uzunligi bilan aniqlanadi. 5.48 yo‘l belgisi o‘rnatilgan ko‘cha va yo‘llarda o‘rnatilishi lozimligini bildiradi.', '5.18_resize-min.png.webp', 144),
('5.19.1 – 5.19.4', 'Axborot belgilari', 'Oxiri berk yo‘l', 'Yo‘lning ko‘rsatilgan yo‘nalishda oxiri berkligini bildiradi.', '5.19.1_resize-min.png.webp', 145),
('5.20.1', 'Axborot belgilari', 'Yo‘nalishlarning dastlabki ko‘rsatkichi', '', '5.20.1.2_resize-min.png.webp', 146),
('5.20.2', 'Axborot belgilari', 'Yo‘nalishlarning dastlabki ko‘rsatkichi', '', '5.20.2_resize-min.png.webp', 147),
('5.20.3', 'Axborot belgilari', 'Harakatlanish chizmasi', 'Chorrahada ayrim yo‘nalishlarda harakatlanish taqiqlangan bo‘lsa harakatlanish yo‘nalishi yoki murakkab chorrahalarda ruxsat etilgan harakatlanish yo‘nalishini bildiradi.', '5.20.3_resize-min.png.webp', 148),
('5.20.4', 'Axborot belgilari', 'Yo‘llarining bir sathda kesishmaydigan qismlarida burilish yoki qayrilib olish yo‘nalish ko‘rsatkichi', 'Avtomobil yo‘llarning bir sathda kesishmaydigan qismlarida yer ostidan yoki yer ustidan transport vositalarining burilish va qayrilib olish yo‘nalishini ko‘rsatish uchun qo‘llaniladi.', '5.20.4_resize-min-300x123.png.webp', 149),
('5.20.5', 'Axborot belgilari', 'Xizmat ko‘rsatish maydoni', '', '5.20.5_resize-min.png.webp', 150),
('5.21.1', 'Axborot belgilari', 'Yo‘nalish ko‘rsatkichi', '', '5.21_resize-min.png.webp', 151),
('5.21.2', 'Axborot belgilari', 'Yo‘nalishlar ko‘rsatkichi', 'Ko‘rsatilgan manzillarga harakatlanish yo‘nalishlarini bildiradi. Belgilarda manzillargacha bo‘lgan masofa (km) ko‘rsatilishi, avtomagistrallar, aeroportlar va boshqa ramziy belgilar tasvirlangan bo‘lishi mumkin.', '5.21.2_resize-min.png.webp', 152),
('5.22', 'Axborot belgilari', 'Aholi punktining boshlanishi', 'Ushbu Qoidalarning aholi punktlarida harakatlanish tartibini belgilovchi talablariga amal qilinadigan joylarning nomi hamda uning boshlanishini bildiradi.', '5.22_resize-min.png.webp', 153),
('5.23', 'Axborot belgilari', 'Aholi punktining oxiri', 'Ushbu Qoidalarning aholi punktlarida harakatlanish tartib-talablari bekor qilingan joyni bildiradi.', '5.23_resize-min.png.webp', 154),
('5.25', 'Axborot belgilari', 'Aholi punktining oxiri', '5.24 yo‘l belgisi bilan ko‘rsatilgan aholi punktining oxirini bildiradi.', '5.25.1_resize-min-300x62.png.webp', 155),
('5.26', 'Axborot belgilari', 'Manzil nomi', 'Aholi punktlaridan boshqa manzillarning nomini bildiradi (daryo, ko‘l, dovon, xushmanzara joy va boshqalar).', '5.26_resize-min.png.webp', 156),
('5.27', 'Axborot belgilari', 'Masofalar ko‘rsatkichi', 'Yo‘nalish bo‘yicha joylashgan aholi punktlarigacha bo‘lgan masofani bildiradi (km).', '5.27_resize-min.png.webp', 157),
('5.28', 'Axborot belgilari', 'Kilometr belgisi', 'Yo‘lning boshi yoki oxirigacha bo‘lgan masofani bildiradi (km).', '5.28_resize-min.png.webp', 158),
('5.29.1', 'Axborot belgilari', 'Yo‘l raqami', 'Yo‘lga berilgan raqam', '5.29.1_resize-min.png.webp', 159),
('5.29.2', 'Axborot belgilari', 'Yo‘l raqami', 'Yo‘lning raqami va yo‘nalishini bildiradi.', '5.29.2_resize-min.png.webp', 160),
('5.30.1 – 5.30.3', 'Axborot belgilari', 'Yuk avtomobillari uchun harakatlanish yo‘nalishi', 'Chorrahada yuk avtomobillari, traktorlar va o‘ziyurar moslamalarga biror yo‘nalishda harakatlanish taqiqlangan bo‘lsa, bunday transport vositalariga tavsiya etilgan harakatlanish yo‘nalishlari ko‘rsatadi.', '5.30_resize-min.png.webp', 161),
('5.31', 'Axborot belgilari', 'Aylanib o‘tish tasviri', 'Harakatlanish uchun vaqtincha yopib qo‘yilgan yo‘l qismini chetlab o‘tish chizmasi.', '5.31_resize-min.png.webp', 162),
('5.32.1 – 5.32.3', 'Axborot belgilari', 'Chetlab o‘tish yo‘nalishi', 'Harakatlanish vaqtincha yopib qo‘yilgan yo‘l qismini chetlab o‘tish yo‘nalishini bildiradi.', '5.32_resize-min.png.webp', 163),
('5.33', 'Axborot belgilari', 'To‘xtash chizig‘i', 'Svetoforning (tartibga soluvchining) taqiqlovchi ishorasida transport vositalari to‘xtaydigan yo‘nalishini bildiradi.', '5.33_resize-min.png.webp', 164),
('5.34.1 – 5.34.2', 'Axborot belgilari', 'Boshqa qatnov qismiga qayta tizilishning boshlang‘ich ko‘rsatkichi', 'Ajratuvchi bo‘lagi bo‘lgan yo‘lning harakatlanish uchun yopiq hududini aylanib o‘tish yoki o‘ng tomondagi qatnov qismiga qaytish uchun harakatlanish yo‘nalishini bildiradi.', '5.34.1_resize-min.png.webp', 165),
('5.35', 'Axborot belgilari', 'Reversiv harakatlanish', 'Bir yoki bir necha tasmalarda harakatlanish yo‘nalishi qarama-qarshi tomonga o‘zgarishi mumkin bo‘lgan yo‘l qismining boshlanishini bildiradi.', '5.35_resize-min.png.webp', 166),
('5.36', 'Axborot belgilari', 'Reversiv harakatlanishning oxiri', '', '5.36_resize-min.png.webp', 167),
('5.37', 'Axborot belgilari', 'Reversiv harakatlanish yo‘liga chiqish', '', '5.37_resize-min.png.webp', 168),
('5.38', 'Axborot belgilari', 'Turar joy dahasi', 'Yo‘l harakati qoidalarining turar joy dahalarida harakatlanish tartibi o‘rnatilgan yo‘l.', '5.38_resize-min.png.webp', 169),
('5.39', 'Axborot belgilari', 'Turar joy dahasining oxiri', '', '5.39_resize-min.png.webp', 170),
('5.40', 'Axborot belgilari', 'Falokatli holatlar uchun kirish yo‘li', 'Yo‘l harakati ushbu Qoidalaridagi 128-bandda ko‘rsatilgan holatlarda foydalaniladigan yo‘l.', '5.40_resize-min.png.webp', 171),
('5.41', 'Axborot belgilari', 'Foto va video qayd etish', 'Yo‘llarda avtomobil haydovchilari Qoidalar talabiga rioya etishi elektron qurilmalar yordamida nazorat qilinayotganligini bildiruvchi yo‘l belgisi. Ushbu yo‘l belgisi Qoidalar talabiga rioya etilishi statsionar elektron qurilmalar orqali nazoratga olingan joylarga o‘rnatiladi.', '5.41_resize-min.png.webp', 172),
('5.42', 'Axborot belgilari', 'Qizil chiroqda o‘ngga harakatlanish', 'Transport svetofori qizil chirog‘ining o‘ng yoniga 5.42 yo‘l belgisi o‘rnatilgan bo‘lsa, transport vositalarining haydovchilari svetoforning taqiqlovchi ishorasi yonib turganda, barcha xavfsizlik choralarini ko‘rgan holda o‘ngga burilishlari mumkin. Bunda ular harakat yo‘nalishi bo‘yicha va burilayotgan ko‘chani kesib o‘tayotgan piyodalarga hamda boshqa transport vositalariga yo‘l berishlari shart.', '5.42_resize-min.png.webp', 173),
('5.43', 'Axborot belgilari', 'Radar', 'Yo‘llarda avtomobil haydovchilari belgilangan tezlikka rioya etishi radarlar yordamida nazorat qilinayotganligini bildiruvchi yo‘l belgisi. Ushbu yo‘l belgisi belgilangan harakatlanish tezligi statsionar maxsus texnika vositalari yordamida nazoratga olingan joylarga o‘rnatiladi. Shuningdek, viloyat, tuman, shaharlar boshlanadigan joylardagi ko‘cha va yo‘llarda harakatlanish tezligi mobil radarlar yordamida nazorat qilinayotganligi to‘g‘risida haydovchilarni ogohlantirish maqsadida o‘rnatilishi mumkin.', '5.43_resize-min.png.webp', 174),
('5.44', 'Axborot belgilari', 'Velosipedchilar uchun tasma', '', '5.44_resize-min.png.webp', 175),
('5.45', 'Axborot belgilari', 'Velosipedchilar uchun tasmaning oxiri', '', '5.45_resize-min.png.webp', 176),
('5.46', 'Axborot belgilari', 'Maktab', 'Maktab yoki maktabgacha ta’lim tashkilotlari oldida o‘rnatiladi.', '5.46_resize-min.png.webp', 177),
('5.47', 'Axborot belgilari', 'Turizm obyektlari yo‘nalish ko‘rsatgichi', 'Turizm obyektlari joylashgan manzillarga harakatlanish yo‘nalishlarini bildiradi. Belgilarda manzillargacha bo‘lgan masofa (km) ko‘rsatilishi, temir yo‘l vokzallari, aeroportlar va boshqa turizm obyektlari ramziy belgilari tasvirlangan bo‘lishi mumkin.', '5.47_resize-min.png.webp', 178),
('5.47.1', 'Axborot belgilari', 'Turizm obyektlari', '', '5.47_resize-min.png.webp', 179),
('5.47.2', 'Axborot belgilari', 'Turizm axborot markazi', '', '5.47_resize-min.png.webp', 180),
('5.48', 'Axborot belgilari', 'Baland piyodalar o‘tish joyi', '5.16.1-5.16.2 yo‘l belgilari bilan birga qo‘llaniladi.', '5.48.webp', 181),
('6.1', 'Xizmat ko’rsatish belgilari', 'Tibbiy yordam ko‘rsatish joyi', '', '6.1_resize-min.png.webp', 182),
('6.2', 'Xizmat ko’rsatish belgilari', 'Shifoxona', '', '6.2_resize-min.png.webp', 183),
('6.3.1', 'Xizmat ko’rsatish belgilari', 'Avtomobillarga yonilg‘i quyish shoxobchasi', '', '6.3.1_resize-min.png.webp', 184),
('6.3.2', 'Xizmat ko’rsatish belgilari', 'Avtomobillarga ko‘p tarmoqli yonilg‘i quyish shoxobchasi', '', '6.3.2_resize-min.png.webp', 185),
('6.3.3', 'Xizmat ko’rsatish belgilari', 'Elektromobillarni quvvatlash shaxobchasi', '', '6.3.3_resize-min.png.webp', 186),
('6.4', 'Xizmat ko’rsatish belgilari', 'Avtomobillarga texnik xizmat ko‘rsatish joyi', '', '6.4_resize-min.png.webp', 187),
('6.5', 'Xizmat ko’rsatish belgilari', 'Avtomobillarni yuvish joyi', '', '6.5_resize-min.png.webp', 188),
('6.6', 'Xizmat ko’rsatish belgilari', 'Telefon', '', '6.6_resize-min.png.webp', 189),
('6.7', 'Xizmat ko’rsatish belgilari', 'Oshxona', '', '6.7_resize-min.png.webp', 190),
('6.8', 'Xizmat ko’rsatish belgilari', 'Ichimlik suvi', '', '6.8_resize-min.png.webp', 191),
('6.9', 'Xizmat ko’rsatish belgilari', 'Mehmonxona yoki motel', '', '6.9_resize-min.png.webp', 192),
('6.10', 'Xizmat ko’rsatish belgilari', 'Kemping', '', '6.10_resize-min.png.webp', 193),
('6.11', 'Xizmat ko’rsatish belgilari', 'Dam olish joyi', '', '6.11_resize-min.png.webp', 194),
('6.12', 'Xizmat ko’rsatish belgilari', 'YPX maskani', '', '6.12_resize-min.png.webp', 195),
('6.13', 'Xizmat ko’rsatish belgilari', 'Avtotashuvchilarning nazorat punkti', '', '6.13_resize-min.png.webp', 196),
('6.14', 'Xizmat ko’rsatish belgilari', 'Hojatxona', '', '6.14_resize-min.png.webp', 197),
('6.15', 'Xizmat ko’rsatish belgilari', 'Chiqindi yig‘ish joyi', '', '6.15_resize-min.png.webp', 198),
('6.16', 'Xizmat ko’rsatish belgilari', 'Cho‘milish havzasi', '', '6.16_resize-min.png.webp', 199),
('6.17', 'Xizmat ko’rsatish belgilari', 'Ichki ishlar bo‘limi', '', '6.17_resize-min.png.webp', 200),
('6.18', 'Xizmat ko’rsatish belgilari', 'Radio aloqasi', '', '6.18_resize-min.png.webp', 201),
('6.19', 'Xizmat ko’rsatish belgilari', 'Jome’ masjidi', '', '6.19_resize-min.png.webp', 202),
('6.20', 'Xizmat ko’rsatish belgilari', 'Cherkov', '', '6.20_resize-min.png.webp', 203),
('6.21', 'Xizmat ko’rsatish belgilari', 'Ibodatxona', '', '6.21_resize-min.png.webp', 204),
('6.22', 'Xizmat ko’rsatish belgilari', 'Temir yo‘l vokzali', '', '6.22_resize-min.png.webp', 205),
('6.23', 'Xizmat ko’rsatish belgilari', 'Aeroport', '', '6.23_resize-min.png.webp', 206),
('6.24', 'Xizmat ko’rsatish belgilari', 'Bozor', '', '6.24_resize-min.png.webp', 207),
('6.25', 'Xizmat ko’rsatish belgilari', 'Turistik axborot markazi', '', '6.25_resize-min.png.webp', 208),
('6.26', 'Xizmat ko’rsatish belgilari', 'Qo‘riqxona', '', '6.26_resize-min.png.webp', 209),
('6.27', 'Xizmat ko’rsatish belgilari', 'Manzarali joy', '', '6.27_resize-min.png.webp', 210),
('6.28', 'Xizmat ko’rsatish belgilari', 'Me’morchilik yodgorligi', '', '6.28_resize-min.png.webp', 211),
('7.1.1', 'Qo’shimcha axborot belgilari', 'Obyektgacha bo‘lgan masofa', 'Belgidan yo‘lning xavfli joyi, yo‘l harakatiga tegishli cheklovlar kiritiladigan joyi yoki harakat yo‘nalishi bo‘yicha oldindagi muayyan joygacha bo‘lgan masofani ko‘rsatadi.', '7.1.1_resize-min.png.webp', 212),
('7.1.2', 'Qo’shimcha axborot belgilari', 'Obyektgacha bo‘lgan masofa', 'Aholi punktlaridan tashqarida chorraha oldiga 2.5. yo‘l belgisi o‘rnatilgan bo‘lsa, 2.4. yo‘l belgisi bilan o‘rnatilib, chorrahagacha bo‘lgan masofani ko‘rsatadi.', '7.1.2_resize-min.png.webp', 213),
('7.1.3 – 7.1.4', 'Qo’shimcha axborot belgilari', 'Obyektgacha bo‘lgan masofa', 'Yo‘ldan chetda joylashgan manzilgacha bo‘lgan masofani bildiradi.', '7.1.3_resize-min.png.webp', 214),
('7.2.1', 'Qo’shimcha axborot belgilari', 'Ta’sir oralig‘i', 'Ogohlantiruvchi belgilar bilan belgilangan xavfli joyning uzunligini yoki taqiqlovchi va axborot-ko‘rsatkich belgilarining ta’sir oralig‘ini ko‘rsatadi.', '7.2.1_resize-min.png.webp', 215),
('7.2.2', 'Qo’shimcha axborot belgilari', 'Ta’sir oralig‘i', '3.27 — 3.30 taqiqlovchi belgilarining ta’siri saqlangan oraliqni ko‘rsatadi.', '7.2.2_resize-min-150x300.png.webp', 216),
('7.2.3', 'Qo’shimcha axborot belgilari', 'Ta’sir oralig‘i', '3.27 — 3.30 taqiqlovchi belgilarining ta’sir oralig‘i oxirini ko‘rsatadi.', '7.2.3_resize-min-150x300.png.webp', 217),
('7.2.4', 'Qo’shimcha axborot belgilari', 'Ta’sir oralig‘i', 'Haydovchilarga ularning 3.27 — 3.30 yo‘l belgilari ta’sir doirasida ekanliklari haqida axborot beradi.', '7.2.4_resize-min-150x300.png.webp', 218),
('7.2.5 – 7.2.6', 'Qo’shimcha axborot belgilari', 'Ta’sir oralig‘i', 'Maydon, binolar oldi va shunga o‘xshash joylar chetida to‘xtash va to‘xtab turish taqiqlanganda 3.27 — 3.30 belgilarining ta’sir oralig‘i va yo‘nalishini ko‘rsatadi.', '7.2.5_resize-min.png.webp', 219),
('7.3.1 – 7.3.3', 'Qo’shimcha axborot belgilari', 'Ta’sir yo‘nalishlari', 'Chorraha oldida o‘rnatilgan belgilarning ta’sir yo‘nalishini yoki bevosita yo‘l yaqinida joylashgan manzillarga harakatlanish yo‘nalishini ko‘rsatadi.', '7.3.1_resize-min.png.webp', 220),
('7.4.1 – 7.4.10', 'Qo’shimcha axborot belgilari', 'Transport vositasining turi', 'Belgining ta’siri joriy etilgan transport vositalari turini ko‘rsatadi. 7.4.1 belgi bilan o‘rnatilgan yo‘l belgisining ta’siri yuk tashuvchi, shu jumladan, tirkamali, to‘liq vazni 3,5 tonnadan ortiq bo‘lgan transport vositalariga, 7.4.3 belgi bilan o‘rnatilgan yo‘l belgisining ta’siri yengil avtomobillarga, 7.4.9 elektromobillarga, 7.4.10 yo‘nalishsiz taksilarga, shuningdek, to‘liq vazni 3,5 tonnagacha bo‘lgan yuk tashuvchi transport vositalariga tatbiq etiladi.', '7.4.1_resize-min.png.webp', 221),
('7.5.1', 'Qo’shimcha axborot belgilari', 'Shanba, yakshanba va bayram kunlari', '', '7.5.1_resize-min.png.webp', 222),
('7.5.2', 'Qo’shimcha axborot belgilari', 'Ish kunlari', '', '7.5.2_resize-min.png.webp', 223),
('7.5.3', 'Qo’shimcha axborot belgilari', 'Hafta kunlari', 'Belgiga haftaning qaysi kunlari amal qilinishi ko‘rsatilgan.', '7.5.3_resize-min.png.webp', 224),
('7.5.4', 'Qo’shimcha axborot belgilari', 'Amal qilish vaqti', 'Belgiga kunning qaysi vaqtida amal qilishni ko‘rsatadi.', '7.5.4_resize-min.png.webp', 225),
('7.5.5 – 7.5.7', 'Qo’shimcha axborot belgilari', 'Amal qilish vaqti', 'Belgiga haftaning qaysi kuni va qaysi soatlarida amal qilishni ko‘rsatadi.', '7.5.5_resize-min.png.webp', 226),
('7.6.1 – 7.6.9', 'Qo’shimcha axborot belgilari', 'Transport vositasini to‘xtab turish joyiga qo‘yish usuli', '7.6.1 barcha turdagi transport vositalarini to‘xtab turishi uchun yo‘lning qatnov qismida, trotuar yoniga qo‘yish usulini, 7.6.2 — 7.6.9 trotuar yonidagi to‘xtab turish joyiga yengil avtomobillar va mototsikllarni qo‘yish usulini bildiradi.', '7.6.1_resize-min.png.webp', 227),
('7.7', 'Qo’shimcha axborot belgilari', 'Dvigatelni ishlatmasdan to‘xtab turish joyi', '5.15 belgisi bilan belgilangan to‘xtab turish joyida transport vositalarining dvigatelini ishlatmasdan to‘xtab turishiga ruxsat etilganligini ko‘rsatadi.', '7.7_resize-min.png.webp', 228),
('7.8', 'Qo’shimcha axborot belgilari', 'Pulli xizmat ko‘rsatish joyi', 'To‘lov asosida xizmat ko‘rsatilishini bildiradi.', '7.8_resize-min.png.webp', 229),
('7.9', 'Qo’shimcha axborot belgilari', 'To‘xtab turish muddati cheklangan', '5.15 belgisi o‘rnatilgan to‘xtab turish joyida transport vositalari to‘xtab turishining eng ko‘p muddatini ko‘rsatadi.', '7.9_resize-min.png.webp', 230),
('7.10', 'Qo’shimcha axborot belgilari', 'Avtomobillarni ko‘rikdan o‘tkazish joyi', '5.15 yoki 6.11 belgisi bilan ko‘rsatilgan maydonlarda estakada yoki ko‘zdan kechirish chuqurchalari borligini bildiradi.', '7.10_resize-min.png.webp', 231),
('7.11', 'Qo’shimcha axborot belgilari', 'Ruxsat etilgan to‘la vazni cheklangan', 'Belgining ta’siri ruxsat etilgan to‘la vazni qo‘shimcha-axborot yo‘l belgisida ko‘rsatilgan miqdordan ortiq bo‘lgan transport vositalariga taalluqli ekanligini ko‘rsatadi.', '7.11_resize-min.png.webp', 232),
('7.12', 'Qo’shimcha axborot belgilari', 'Xavfli yo‘l yoqasi', 'Yo‘l ishlari bajarilayotgani sababli yo‘l yoqasiga chiqish xavfli ekanligi haqida ogohlantiradi. 1.23 belgisi bilan qo‘llaniladi.', '7.12_resize-min.png.webp', 233),
('7.13', 'Qo’shimcha axborot belgilari', 'Asosiy yo‘lning yo‘nalishi', 'Chorrahada asosiy yo‘lning yo‘nalishini ko‘rsatadi.', '7.13_resize-min-300x198.png.webp', 234),
('7.14', 'Qo’shimcha axborot belgilari', 'Harakatlanish tasmasi', 'Belgi yoki svetofor ta’siridagi harakatlanish bo‘lagini ko‘rsatadi.', '7.14_resize-min.png.webp', 235),
('7.15', 'Qo’shimcha axborot belgilari', 'Ko‘zi ojiz piyodalar', '1.20, 5.16.1, 5.16.2 belgilari hamda svetofor bilan birga qo‘llaniladi, piyodalar o‘tish joyidan ko‘zi ojiz piyodalar foydalanishi mumkinligi haqida ogohlantiradi.', '7.15_resize-min.png.webp', 236),
('7.16', 'Qo’shimcha axborot belgilari', 'Nam qoplama', 'Belgi qatnov qismining qoplamasi nam bo‘lgan vaqtda ta’sir etishini ko‘rsatadi.', '7.16_resize-min.png.webp', 237),
('7.17', 'Qo’shimcha axborot belgilari', 'Nogironlar', '5.15 belgisi bilan qo‘llaniladi. To‘xtab turish joyi (yoki uning bir qismi) ushbu Qoidalarning 176-bandiga muvofiq “Nogiron” taniqlik belgisi o‘rnatilgan transport vositalari uchun ajratilganligini ko‘rsatadi.', '7.17_resize-min.png.webp', 238),
('7.18', 'Qo’shimcha axborot belgilari', 'Nogironlar mustasno', 'Belgilarning ta’siri ushbu Qoidalarning 175-bandiga muvofiq “Nogiron” taniqlik belgisi o‘rnatilgan transport vositalariga joriy etilmaydi.', '7.18_resize-min.png.webp', 239),
('7.19', 'Qo’shimcha axborot belgilari', 'Foto va video qayd etish', 'Yo‘l harakati qatnashchilarining harakatlari maxsus avtomatlashtirilgan foto va video qayd etish texnika vositalari orqali qayd etilayotganligini bildiradi. Ogohlantiruvchi, imtiyoz, taqiqlovchi, buyuruvchi va axborot ishora belgilari bilan birgalikda qo‘llaniladi.', '7.19_resize-min.png.webp', 240),
('7.20', 'Qo’shimcha axborot belgilari', 'Xavfli yuk toifasi', 'Xavfli yuk toifasining (toifalarining) raqamini ko‘rsatadi.', '7.20_resize-min.png.webp', 241),
('7.21', 'Qo’shimcha axborot belgilari', 'Evakuator ishlamoqda', '3.27 — 3.30 yo‘l belgilari ta’sir oralig‘ida to‘xtagan transport vositalari majburiy evakuatsiya qilinishini ko‘rsatadi.', '7.21_resize-min.png.webp', 242),
('7.22.1 – 7.22.3', 'Qo’shimcha axborot belgilari', 'To‘siq', 'Haydovchilarga to‘siqning uzoqdan ko‘rinishini ta’minlash maqsadida o‘rnatiladi. 4.2.1 — 4.2.3 yo‘l belgilari bilan birgalikda o‘rnatiladi.', '7.22_resize-min-141x300.png.webp', 243),
('7.23', 'Qo’shimcha axborot belgilari', 'Navbat bilan o‘tish', '', '7.23_resize-min.png.webp', 244),
('7.24', 'Qo’shimcha axborot belgilari', 'Transport vositasining davlat raqami', '', '7.24_resize-min.png', 245),
('7.25', 'Qo’shimcha axborot belgilari', 'Faqat xizmat avtomobillari', '', '7.25_resize-min.png.webp', 246),
('7.26', 'Qo’shimcha axborot belgilari', 'Sun’iy notekislik', '', '7.26_resize-min.png.webp', 247);
