name: Deploy Supabase Edge Functions

on:
  push:
    branches: ["main"]
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Edge Functions
        run: supabase functions deploy phone-check --no-verify-jwt --project-ref ziqzprosgzevkdfwyotl
        env:
          SUPABASE_ACCESS_TOKEN: sbp_8f032e21ab111888f5436fc1af748032d34215a8
